# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: rugroupy-server 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = 'rugroupy-server'
  s.version = '0.2.1'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']
  s.authors = ['Ryan Wynn']
  s.date = '2018-03-08'
  s.description = 'a library which uses the map-reduce capabilities of mongodb to group entities based on tags.'
  s.email = 'ryan.m.wynn@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.rdoc'
  ]
  s.files = [
    'lib/rugroupy/mongo.rb',
    'lib/rugroupy/server.rb',
    'lib/rugroupy/server_default.rb'
  ]
  s.homepage = 'http://github.com/rwynn/rugroupy-server'
  s.licenses = ['MIT']
  s.rubygems_version = '2.2.2'
  s.summary = 'find things that are similiar to things'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('bson', ['>= 0'])
      s.add_runtime_dependency('json', ['>= 0'])
      s.add_runtime_dependency('mongo', ['>= 0'])
      s.add_runtime_dependency('rugroupy', ['>= 0'])
      s.add_runtime_dependency('sinatra', ['>= 0'])
      s.add_development_dependency('bundler', ['>= 0'])
      s.add_development_dependency('httparty', ['>= 0'])
      s.add_development_dependency('jeweler', ['>= 0'])
      s.add_development_dependency('shoulda', ['>= 0'])
    else
      s.add_dependency('bson', ['>= 0'])
      s.add_dependency('bundler', ['>= 0'])
      s.add_dependency('httparty', ['>= 0'])
      s.add_dependency('jeweler', ['>= 0'])
      s.add_dependency('json', ['>= 0'])
      s.add_dependency('mongo', ['>= 0'])
      s.add_dependency('rugroupy', ['>= 0'])
      s.add_dependency('shoulda', ['>= 0'])
      s.add_dependency('sinatra', ['>= 0'])
    end
  else
    s.add_dependency('bson', ['>= 0'])
    s.add_dependency('json', ['>= 0'])
    s.add_dependency('mongo', ['>= 0'])
    s.add_dependency('rugroupy', ['>= 0'])
    s.add_dependency('sinatra', ['>= 0'])
    s.add_dependency('sinatra', ['>= 0'])
    s.add_dependency('sinatra', ['>= 0'])
    s.add_dependency('sinatra', ['>= 0'])
    s.add_dependency('sinatra', ['>= 0'])
  end
end
